"""empty message

Revision ID: 5a098d85cecc
Revises: 
Create Date: 2018-05-03 13:51:21.673721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a098d85cecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_utilisateur_username'), 'utilisateur', ['username'], unique=True)
    op.create_table('image',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.username'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_index(op.f('ix_utilisateur_username'), table_name='utilisateur')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
